import React from 'react'
import Homepage from './Component/Homepage'
import './Component/page.css'
export default function App() {
  return (
    <div>
      <Homepage />
      <h1>Vijay Biography Vijay (aka) Joseph Vijay is a Tamil film actor and playback singer. As a child artist, he played many minor, uncredited roles in films produced by his father, S. A. Chandrasekhar. Post-Thirumalai, he began portraying a stereotypical acting manner, much like Rajinikanth and M. G. Ramachandran. Vijay has more recently become a charismatic film star and has thus developed a large fan following for himself. He is one of the highest-paid actors in the Tamil film industry, and he is referred to by fans and the media as Thalapathy. Personal Life Joseph Vijay Chandrasekhar was born on June 22, 1974, to film producer and director S. A. Chandrasekhar and Shoba Chandrasekhar, a playback singer. He had a sister named Vidhya Chandrasekhar, who died at the age of two. The film Sukran depicted Vidhya Chandrasekhar's story. Vijay went on to study visual communications at Loyola College in Chennai, where he met fellow actors Surya Sivakumar, Yuvan Shankar Raja, Karthik Raja, and Vishnuvardhan. He married the Sri Lankan Tamil, Sangeetha Sornalingam, on August 25, 1999. She was a die-hard fan of Vijay and sought interest in marrying him. They have two children, a son named Jason Sanjay, born on August 26, 2000 in London, and a daughter named Divya Saasha, born on September 9, 2005 in Chennai. Career Vijay's first role was in the drama, he continued to perform as a child artist in films until Ithu Engal Neethi, directed by his father, S. A. Chandrasekhar. Vijay debuted as a lead actor in the 1992 film Naalaya Theerpu, produced by his father, and then he co-starred with Vijayakanth in the film Sendhoorapandi. This film helped Vijay become popular in the interior areas of Tamil Nadu. He received his breakthrough in the film Poove Unakkaga, which was directed by Vikraman. He made a friendly appearance in the 2012 Bollywood film Rowdy Rathore, starring Akshay Kumar and directed by Prabhu Deva. As a playback singer, Vijay has sung over thirty songs in his films, and he completes his 25 years of singing in 2019.

      Read more at: https://www.filmibeat.com/celebs/vijay-tamil-actor/biography.html</h1>
      <h1>Vijay Biography Vijay (aka) Joseph Vijay is a Tamil film actor and playback singer. As a child artist, he played many minor, uncredited roles in films produced by his father, S. A. Chandrasekhar. Post-Thirumalai, he began portraying a stereotypical acting manner, much like Rajinikanth and M. G. Ramachandran. Vijay has more recently become a charismatic film star and has thus developed a large fan following for himself. He is one of the highest-paid actors in the Tamil film industry, and he is referred to by fans and the media as Thalapathy. Personal Life Joseph Vijay Chandrasekhar was born on June 22, 1974, to film producer and director S. A. Chandrasekhar and Shoba Chandrasekhar, a playback singer. He had a sister named Vidhya Chandrasekhar, who died at the age of two. The film Sukran depicted Vidhya Chandrasekhar's story. Vijay went on to study visual communications at Loyola College in Chennai, where he met fellow actors Surya Sivakumar, Yuvan Shankar Raja, Karthik Raja, and Vishnuvardhan. He married the Sri Lankan Tamil, Sangeetha Sornalingam, on August 25, 1999. She was a die-hard fan of Vijay and sought interest in marrying him. They have two children, a son named Jason Sanjay, born on August 26, 2000 in London, and a daughter named Divya Saasha, born on September 9, 2005 in Chennai. Career Vijay's first role was in the drama, he continued to perform as a child artist in films until Ithu Engal Neethi, directed by his father, S. A. Chandrasekhar. Vijay debuted as a lead actor in the 1992 film Naalaya Theerpu, produced by his father, and then he co-starred with Vijayakanth in the film Sendhoorapandi. This film helped Vijay become popular in the interior areas of Tamil Nadu. He received his breakthrough in the film Poove Unakkaga, which was directed by Vikraman. He made a friendly appearance in the 2012 Bollywood film Rowdy Rathore, starring Akshay Kumar and directed by Prabhu Deva. As a playback singer, Vijay has sung over thirty songs in his films, and he completes his 25 years of singing in 2019.

      Read more at: https://www.filmibeat.com/celebs/vijay-tamil-actor/biography.html</h1>
      <h1>Vijay Biography Vijay (aka) Joseph Vijay is a Tamil film actor and playback singer. As a child artist, he played many minor, uncredited roles in films produced by his father, S. A. Chandrasekhar. Post-Thirumalai, he began portraying a stereotypical acting manner, much like Rajinikanth and M. G. Ramachandran. Vijay has more recently become a charismatic film star and has thus developed a large fan following for himself. He is one of the highest-paid actors in the Tamil film industry, and he is referred to by fans and the media as Thalapathy. Personal Life Joseph Vijay Chandrasekhar was born on June 22, 1974, to film producer and director S. A. Chandrasekhar and Shoba Chandrasekhar, a playback singer. He had a sister named Vidhya Chandrasekhar, who died at the age of two. The film Sukran depicted Vidhya Chandrasekhar's story. Vijay went on to study visual communications at Loyola College in Chennai, where he met fellow actors Surya Sivakumar, Yuvan Shankar Raja, Karthik Raja, and Vishnuvardhan. He married the Sri Lankan Tamil, Sangeetha Sornalingam, on August 25, 1999. She was a die-hard fan of Vijay and sought interest in marrying him. They have two children, a son named Jason Sanjay, born on August 26, 2000 in London, and a daughter named Divya Saasha, born on September 9, 2005 in Chennai. Career Vijay's first role was in the drama, he continued to perform as a child artist in films until Ithu Engal Neethi, directed by his father, S. A. Chandrasekhar. Vijay debuted as a lead actor in the 1992 film Naalaya Theerpu, produced by his father, and then he co-starred with Vijayakanth in the film Sendhoorapandi. This film helped Vijay become popular in the interior areas of Tamil Nadu. He received his breakthrough in the film Poove Unakkaga, which was directed by Vikraman. He made a friendly appearance in the 2012 Bollywood film Rowdy Rathore, starring Akshay Kumar and directed by Prabhu Deva. As a playback singer, Vijay has sung over thirty songs in his films, and he completes his 25 years of singing in 2019.

      Read more at: https://www.filmibeat.com/celebs/vijay-tamil-actor/biography.html</h1>
      <h1>Vijay Biography Vijay (aka) Joseph Vijay is a Tamil film actor and playback singer. As a child artist, he played many minor, uncredited roles in films produced by his father, S. A. Chandrasekhar. Post-Thirumalai, he began portraying a stereotypical acting manner, much like Rajinikanth and M. G. Ramachandran. Vijay has more recently become a charismatic film star and has thus developed a large fan following for himself. He is one of the highest-paid actors in the Tamil film industry, and he is referred to by fans and the media as Thalapathy. Personal Life Joseph Vijay Chandrasekhar was born on June 22, 1974, to film producer and director S. A. Chandrasekhar and Shoba Chandrasekhar, a playback singer. He had a sister named Vidhya Chandrasekhar, who died at the age of two. The film Sukran depicted Vidhya Chandrasekhar's story. Vijay went on to study visual communications at Loyola College in Chennai, where he met fellow actors Surya Sivakumar, Yuvan Shankar Raja, Karthik Raja, and Vishnuvardhan. He married the Sri Lankan Tamil, Sangeetha Sornalingam, on August 25, 1999. She was a die-hard fan of Vijay and sought interest in marrying him. They have two children, a son named Jason Sanjay, born on August 26, 2000 in London, and a daughter named Divya Saasha, born on September 9, 2005 in Chennai. Career Vijay's first role was in the drama, he continued to perform as a child artist in films until Ithu Engal Neethi, directed by his father, S. A. Chandrasekhar. Vijay debuted as a lead actor in the 1992 film Naalaya Theerpu, produced by his father, and then he co-starred with Vijayakanth in the film Sendhoorapandi. This film helped Vijay become popular in the interior areas of Tamil Nadu. He received his breakthrough in the film Poove Unakkaga, which was directed by Vikraman. He made a friendly appearance in the 2012 Bollywood film Rowdy Rathore, starring Akshay Kumar and directed by Prabhu Deva. As a playback singer, Vijay has sung over thirty songs in his films, and he completes his 25 years of singing in 2019.

      Read more at: https://www.filmibeat.com/celebs/vijay-tamil-actor/biography.html</h1>
      <h1>Vijay Biography Vijay (aka) Joseph Vijay is a Tamil film actor and playback singer. As a child artist, he played many minor, uncredited roles in films produced by his father, S. A. Chandrasekhar. Post-Thirumalai, he began portraying a stereotypical acting manner, much like Rajinikanth and M. G. Ramachandran. Vijay has more recently become a charismatic film star and has thus developed a large fan following for himself. He is one of the highest-paid actors in the Tamil film industry, and he is referred to by fans and the media as Thalapathy. Personal Life Joseph Vijay Chandrasekhar was born on June 22, 1974, to film producer and director S. A. Chandrasekhar and Shoba Chandrasekhar, a playback singer. He had a sister named Vidhya Chandrasekhar, who died at the age of two. The film Sukran depicted Vidhya Chandrasekhar's story. Vijay went on to study visual communications at Loyola College in Chennai, where he met fellow actors Surya Sivakumar, Yuvan Shankar Raja, Karthik Raja, and Vishnuvardhan. He married the Sri Lankan Tamil, Sangeetha Sornalingam, on August 25, 1999. She was a die-hard fan of Vijay and sought interest in marrying him. They have two children, a son named Jason Sanjay, born on August 26, 2000 in London, and a daughter named Divya Saasha, born on September 9, 2005 in Chennai. Career Vijay's first role was in the drama, he continued to perform as a child artist in films until Ithu Engal Neethi, directed by his father, S. A. Chandrasekhar. Vijay debuted as a lead actor in the 1992 film Naalaya Theerpu, produced by his father, and then he co-starred with Vijayakanth in the film Sendhoorapandi. This film helped Vijay become popular in the interior areas of Tamil Nadu. He received his breakthrough in the film Poove Unakkaga, which was directed by Vikraman. He made a friendly appearance in the 2012 Bollywood film Rowdy Rathore, starring Akshay Kumar and directed by Prabhu Deva. As a playback singer, Vijay has sung over thirty songs in his films, and he completes his 25 years of singing in 2019.

      Read more at: https://www.filmibeat.com/celebs/vijay-tamil-actor/biography.html</h1>
      <h1>Vijay Biography Vijay (aka) Joseph Vijay is a Tamil film actor and playback singer. As a child artist, he played many minor, uncredited roles in films produced by his father, S. A. Chandrasekhar. Post-Thirumalai, he began portraying a stereotypical acting manner, much like Rajinikanth and M. G. Ramachandran. Vijay has more recently become a charismatic film star and has thus developed a large fan following for himself. He is one of the highest-paid actors in the Tamil film industry, and he is referred to by fans and the media as Thalapathy. Personal Life Joseph Vijay Chandrasekhar was born on June 22, 1974, to film producer and director S. A. Chandrasekhar and Shoba Chandrasekhar, a playback singer. He had a sister named Vidhya Chandrasekhar, who died at the age of two. The film Sukran depicted Vidhya Chandrasekhar's story. Vijay went on to study visual communications at Loyola College in Chennai, where he met fellow actors Surya Sivakumar, Yuvan Shankar Raja, Karthik Raja, and Vishnuvardhan. He married the Sri Lankan Tamil, Sangeetha Sornalingam, on August 25, 1999. She was a die-hard fan of Vijay and sought interest in marrying him. They have two children, a son named Jason Sanjay, born on August 26, 2000 in London, and a daughter named Divya Saasha, born on September 9, 2005 in Chennai. Career Vijay's first role was in the drama, he continued to perform as a child artist in films until Ithu Engal Neethi, directed by his father, S. A. Chandrasekhar. Vijay debuted as a lead actor in the 1992 film Naalaya Theerpu, produced by his father, and then he co-starred with Vijayakanth in the film Sendhoorapandi. This film helped Vijay become popular in the interior areas of Tamil Nadu. He received his breakthrough in the film Poove Unakkaga, which was directed by Vikraman. He made a friendly appearance in the 2012 Bollywood film Rowdy Rathore, starring Akshay Kumar and directed by Prabhu Deva. As a playback singer, Vijay has sung over thirty songs in his films, and he completes his 25 years of singing in 2019.

      Read more at: https://www.filmibeat.com/celebs/vijay-tamil-actor/biography.html</h1>
    </div>
  )
}
